#!/usr/bin/env fish

# Set the directory paths for the project and its includes
set build_dir (pwd)"/build/tests"
set include_dir (pwd)"/include"
set external_dir (pwd)"/external"
set tests_dir (pwd)"/tests/cpp"

true

# mkdir build
# cd build
# cmake ..
# make install
# ln -fs (pwd)/static/cec_transformations build/tests/input_data

# The following line puts the debug log file and the test_cec_problem executable file
# under the build/ tree.
cd $build_dir

and rm -f ./cec_test_log.txt ./cec_training_log.txt

and c++ -Wall -Wextra -pedantic -std=c++17 -lstdc++fs \
    -I$include_dir \
    -I$tests_dir \
    -I$external_dir/fmt/include \
    -I$external_dir/clutchlog \
    -I$external_dir/json/include \
    -isystem $external_dir/googletest/googletest/include \
    -isystem $external_dir/googletest/googletest \
    $tests_dir/problem/test_cec_problem.cpp \
    $tests_dir/entrypoint.cpp \
    -o test_cec_problem \
    $build_dir/../lib/libgtest.a -lpthread
and c++ -Wall -Wextra -pedantic -std=c++17 -lstdc++fs \
    -I$include_dir \
    -I$tests_dir \
    -I$external_dir/fmt/include \
    -I$external_dir/clutchlog \
    -I$external_dir/json/include \
    -isystem $external_dir/googletest/googletest/include \
    -isystem $external_dir/googletest/googletest \
    -Wall \
    -Wextra \
    -pedantic \
    -std=c++17 \
    -lstdc++fs \
    -std=gnu++17 \
    -I$external_dir/fmt/include \
    $tests_dir/problem/set_cec_problems.cpp \
    -o ./set_cec_problems \
    $build_dir/../lib/libgtest.a -lpthread

and ./set_cec_problems
and ./test_cec_problem
