# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_init_suite <- function(functions, dimensions, instances) {
    invisible(.Call('_IOHexperimenter_c_init_suite', PACKAGE = 'IOHexperimenter', functions, dimensions, instances))
}

c_init_observer <- function(result_folder, algorithm_name, algorithm_info, complete_triggers, number_interval_triggers, base_evaluation_triggers, number_target_triggers, parameters_name, observer_name) {
    invisible(.Call('_IOHexperimenter_c_init_observer', PACKAGE = 'IOHexperimenter', result_folder, algorithm_name, algorithm_info, complete_triggers, number_interval_triggers, base_evaluation_triggers, number_target_triggers, parameters_name, observer_name))
}

get_problem_list <- function() {
    .Call('_IOHexperimenter_get_problem_list', PACKAGE = 'IOHexperimenter')
}

get_dimension_list <- function() {
    .Call('_IOHexperimenter_get_dimension_list', PACKAGE = 'IOHexperimenter')
}

get_suite_info <- function() {
    .Call('_IOHexperimenter_get_suite_info', PACKAGE = 'IOHexperimenter')
}

get_problem_info <- function() {
    .Call('_IOHexperimenter_get_problem_info', PACKAGE = 'IOHexperimenter')
}

c_get_next_problem <- function() {
    .Call('_IOHexperimenter_c_get_next_problem', PACKAGE = 'IOHexperimenter')
}

c_reset_problem <- function() {
    .Call('_IOHexperimenter_c_reset_problem', PACKAGE = 'IOHexperimenter')
}

c_eval <- function(x) {
    .Call('_IOHexperimenter_c_eval', PACKAGE = 'IOHexperimenter', x)
}

c_set_parameters <- function(parameters) {
    invisible(.Call('_IOHexperimenter_c_set_parameters', PACKAGE = 'IOHexperimenter', parameters))
}

c_is_target_hit <- function() {
    .Call('_IOHexperimenter_c_is_target_hit', PACKAGE = 'IOHexperimenter')
}

c_get_evaluations <- function() {
    .Call('_IOHexperimenter_c_get_evaluations', PACKAGE = 'IOHexperimenter')
}

c_get_xopt <- function() {
    .Call('_IOHexperimenter_c_get_xopt', PACKAGE = 'IOHexperimenter')
}

c_get_fopt <- function() {
    .Call('_IOHexperimenter_c_get_fopt', PACKAGE = 'IOHexperimenter')
}

IOHfree <- function() {
    invisible(.Call('_IOHexperimenter_IOHfree', PACKAGE = 'IOHexperimenter'))
}

freeProblem <- function() {
    invisible(.Call('_IOHexperimenter_freeProblem', PACKAGE = 'IOHexperimenter'))
}

freeSuite <- function() {
    invisible(.Call('_IOHexperimenter_freeSuite', PACKAGE = 'IOHexperimenter'))
}

freeObserver <- function() {
    invisible(.Call('_IOHexperimenter_freeObserver', PACKAGE = 'IOHexperimenter'))
}

