# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_init_suite <- function(suite_name, problem_id, instance_id, dimension) {
    .Call('_IOHexperimenter_cpp_init_suite', PACKAGE = 'IOHexperimenter', suite_name, problem_id, instance_id, dimension)
}

cpp_init_logger <- function(output_directory, result_folder, algorithm_name, algorithm_info) {
    .Call('_IOHexperimenter_cpp_init_logger', PACKAGE = 'IOHexperimenter', output_directory, result_folder, algorithm_name, algorithm_info)
}

cpp_get_problem_list <- function() {
    .Call('_IOHexperimenter_cpp_get_problem_list', PACKAGE = 'IOHexperimenter')
}

cpp_get_dimension_list <- function() {
    .Call('_IOHexperimenter_cpp_get_dimension_list', PACKAGE = 'IOHexperimenter')
}

cpp_get_instance_list <- function() {
    .Call('_IOHexperimenter_cpp_get_instance_list', PACKAGE = 'IOHexperimenter')
}

cpp_get_suite_info <- function() {
    .Call('_IOHexperimenter_cpp_get_suite_info', PACKAGE = 'IOHexperimenter')
}

cpp_get_problem_info <- function() {
    .Call('_IOHexperimenter_cpp_get_problem_info', PACKAGE = 'IOHexperimenter')
}

cpp_get_next_problem <- function() {
    .Call('_IOHexperimenter_cpp_get_next_problem', PACKAGE = 'IOHexperimenter')
}

cpp_reset_problem <- function() {
    .Call('_IOHexperimenter_cpp_reset_problem', PACKAGE = 'IOHexperimenter')
}

cpp_int_evaluate <- function(x) {
    .Call('_IOHexperimenter_cpp_int_evaluate', PACKAGE = 'IOHexperimenter', x)
}

cpp_double_evaluate <- function(x) {
    .Call('_IOHexperimenter_cpp_double_evaluate', PACKAGE = 'IOHexperimenter', x)
}

cpp_loggerCOCOInfo <- function() {
    .Call('_IOHexperimenter_cpp_loggerCOCOInfo', PACKAGE = 'IOHexperimenter')
}

cpp_loggerInfo <- function() {
    .Call('_IOHexperimenter_cpp_loggerInfo', PACKAGE = 'IOHexperimenter')
}

cpp_write_line <- function(line_info) {
    .Call('_IOHexperimenter_cpp_write_line', PACKAGE = 'IOHexperimenter', line_info)
}

cpp_logger_target_suite <- function() {
    .Call('_IOHexperimenter_cpp_logger_target_suite', PACKAGE = 'IOHexperimenter')
}

cpp_set_parameters_name <- function(parameters_name) {
    .Call('_IOHexperimenter_cpp_set_parameters_name', PACKAGE = 'IOHexperimenter', parameters_name)
}

cpp_set_parameters_value <- function(parameters) {
    .Call('_IOHexperimenter_cpp_set_parameters_value', PACKAGE = 'IOHexperimenter', parameters)
}

cpp_is_target_hit <- function() {
    .Call('_IOHexperimenter_cpp_is_target_hit', PACKAGE = 'IOHexperimenter')
}

cpp_get_evaluations <- function() {
    .Call('_IOHexperimenter_cpp_get_evaluations', PACKAGE = 'IOHexperimenter')
}

cpp_clear_problem <- function() {
    invisible(.Call('_IOHexperimenter_cpp_clear_problem', PACKAGE = 'IOHexperimenter'))
}

cpp_clear_suite <- function() {
    invisible(.Call('_IOHexperimenter_cpp_clear_suite', PACKAGE = 'IOHexperimenter'))
}

cpp_clear_logger <- function() {
    invisible(.Call('_IOHexperimenter_cpp_clear_logger', PACKAGE = 'IOHexperimenter'))
}

