# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_init_suite <- function(suite_name, problem_id, instance_id, dimension) {
    .Call('_IOHexperimenter_cpp_init_suite', PACKAGE = 'IOHexperimenter', suite_name, problem_id, instance_id, dimension)
}

cpp_init_logger <- function(output_directory, result_folder, algorithm_name, algorithm_info, dat, cdat, tdat, idat) {
    .Call('_IOHexperimenter_cpp_init_logger', PACKAGE = 'IOHexperimenter', output_directory, result_folder, algorithm_name, algorithm_info, dat, cdat, tdat, idat)
}

cpp_get_problem_list <- function() {
    .Call('_IOHexperimenter_cpp_get_problem_list', PACKAGE = 'IOHexperimenter')
}

cpp_get_dimension_list <- function() {
    .Call('_IOHexperimenter_cpp_get_dimension_list', PACKAGE = 'IOHexperimenter')
}

cpp_get_instance_list <- function() {
    .Call('_IOHexperimenter_cpp_get_instance_list', PACKAGE = 'IOHexperimenter')
}

cpp_get_suite_info <- function() {
    .Call('_IOHexperimenter_cpp_get_suite_info', PACKAGE = 'IOHexperimenter')
}

cpp_get_problem_info <- function() {
    .Call('_IOHexperimenter_cpp_get_problem_info', PACKAGE = 'IOHexperimenter')
}

cpp_get_next_problem <- function() {
    .Call('_IOHexperimenter_cpp_get_next_problem', PACKAGE = 'IOHexperimenter')
}

cpp_reset_problem <- function() {
    .Call('_IOHexperimenter_cpp_reset_problem', PACKAGE = 'IOHexperimenter')
}

cpp_int_evaluate <- function(x) {
    .Call('_IOHexperimenter_cpp_int_evaluate', PACKAGE = 'IOHexperimenter', x)
}

cpp_double_evaluate <- function(x) {
    .Call('_IOHexperimenter_cpp_double_evaluate', PACKAGE = 'IOHexperimenter', x)
}

cpp_loggerCOCOInfo <- function() {
    .Call('_IOHexperimenter_cpp_loggerCOCOInfo', PACKAGE = 'IOHexperimenter')
}

cpp_loggerInfo <- function() {
    .Call('_IOHexperimenter_cpp_loggerInfo', PACKAGE = 'IOHexperimenter')
}

cpp_write_line <- function(line_info) {
    .Call('_IOHexperimenter_cpp_write_line', PACKAGE = 'IOHexperimenter', line_info)
}

cpp_do_log <- function(line_info) {
    .Call('_IOHexperimenter_cpp_do_log', PACKAGE = 'IOHexperimenter', line_info)
}

cpp_logger_target_suite <- function() {
    .Call('_IOHexperimenter_cpp_logger_target_suite', PACKAGE = 'IOHexperimenter')
}

cpp_set_parameters_name <- function(parameters_name) {
    .Call('_IOHexperimenter_cpp_set_parameters_name', PACKAGE = 'IOHexperimenter', parameters_name)
}

cpp_set_parameters <- function(parameters_name, parameters) {
    .Call('_IOHexperimenter_cpp_set_parameters', PACKAGE = 'IOHexperimenter', parameters_name, parameters)
}

cpp_add_double_attribute <- function(name, value) {
    .Call('_IOHexperimenter_cpp_add_double_attribute', PACKAGE = 'IOHexperimenter', name, value)
}

cpp_add_int_attribute <- function(name, value) {
    .Call('_IOHexperimenter_cpp_add_int_attribute', PACKAGE = 'IOHexperimenter', name, value)
}

cpp_add_string_attribute1 <- function(name, value) {
    .Call('_IOHexperimenter_cpp_add_string_attribute1', PACKAGE = 'IOHexperimenter', name, value)
}

cpp_delete_attribute <- function(name) {
    .Call('_IOHexperimenter_cpp_delete_attribute', PACKAGE = 'IOHexperimenter', name)
}

cpp_is_target_hit <- function() {
    .Call('_IOHexperimenter_cpp_is_target_hit', PACKAGE = 'IOHexperimenter')
}

cpp_get_evaluations <- function() {
    .Call('_IOHexperimenter_cpp_get_evaluations', PACKAGE = 'IOHexperimenter')
}

cpp_get_optimal <- function() {
    .Call('_IOHexperimenter_cpp_get_optimal', PACKAGE = 'IOHexperimenter')
}

cpp_get_double_upper_bounds <- function() {
    .Call('_IOHexperimenter_cpp_get_double_upper_bounds', PACKAGE = 'IOHexperimenter')
}

cpp_get_double_lower_bounds <- function() {
    .Call('_IOHexperimenter_cpp_get_double_lower_bounds', PACKAGE = 'IOHexperimenter')
}

cpp_get_int_upper_bounds <- function() {
    .Call('_IOHexperimenter_cpp_get_int_upper_bounds', PACKAGE = 'IOHexperimenter')
}

cpp_get_int_lower_bounds <- function() {
    .Call('_IOHexperimenter_cpp_get_int_lower_bounds', PACKAGE = 'IOHexperimenter')
}

cpp_get_optimization_type <- function() {
    .Call('_IOHexperimenter_cpp_get_optimization_type', PACKAGE = 'IOHexperimenter')
}

cpp_clear_problem <- function() {
    invisible(.Call('_IOHexperimenter_cpp_clear_problem', PACKAGE = 'IOHexperimenter'))
}

cpp_clear_suite <- function() {
    invisible(.Call('_IOHexperimenter_cpp_clear_suite', PACKAGE = 'IOHexperimenter'))
}

cpp_clear_logger <- function() {
    invisible(.Call('_IOHexperimenter_cpp_clear_logger', PACKAGE = 'IOHexperimenter'))
}

